openapi: "3.0.0"
info:
  title: Simple Plan API
  version: 1.0.0
paths:
  /accounts:
    post:
      x-controller: accounts
      x-operation: createAccount
      tags:
        - Accounts
      summary: Create an account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - email
                - name
                - username
                - password
              properties:
                email:
                  type: string
                name:
                  type: string
                username:
                  type: string
                password:
                  type: string
                  format: password
            example:
              email: email
              name: name
              username: username
              password: a-password
      responses:
        201:
          description: Account created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid request.
        409:
          description: Account already exists.
        420:
          description: Account password too chill.
    get:
      x-controller: accounts
      x-operation: getAccount
      tags:
        - Accounts
      security:
        - cookieAuth: []
      summary: Get an account.
      responses:
        200:
          description: Authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid request.
        403:
          description: Access denied.
        404:
          description: Account not Found
  /accounts/{username}:
    parameters:
      - $ref: '#/components/parameters/PathUsername'
    # get:
    #   x-controller: accounts
    #   x-operation: getAccount
    #   tags:
    #     - Accounts
    #   security:
    #     - cookieAuth: []
    #   summary: Get an account.
    #   responses:
    #     200:
    #       description: Authenticated.
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/User'
    #     400:
    #       description: Invalid request.
    #     403:
    #       description: Access denied.
    #     404:
    #       description: Account not Found
    patch:
      x-controller: accounts
      x-operation: updateAccount
      tags:
        - Accounts
      security:
        - cookieAuth: []
      summary: Update an account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                name:
                  type: string
                password:
                  type: string
                  format: password
                  minLength: 1
              example:
                email: email
                username: username
                name: name
                password: a-password
      responses:
        200:
          description: Authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid request.
        403:
          description: Access denied.
        404:
          description: Account not Found
    delete:
      x-controller: accounts
      x-operation: deleteAccount
      tags:
        - Accounts
      summary: Delete an account.
      responses:
        404:
          description: Account does not exist
        204:
          description: Account deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /authentication/login:
    x-controller: authentication
    put:
      x-operation: login
      tags:
        - Authentication
      summary: Log in.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              example:
                username: username
                password: a-password
      responses:
        200:
          description: Authenticated.
        400:
          description: Invalid request.
        403:
          description: Access denied.
  /authentication/logout:
    x-controller: authentication
    put:
      x-operation: logout
      tags:
        - Authentication
      summary: Log out.
      responses:
        200:
          description: Logged out.
  /taskLists:
    get:
      # x-controller: taskLists
      # x-operation: getTaskList
      tags:
        - Task Lists
      security:
        - cookieAuth: []
      summary: Get task lists.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskLists'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    post:
      # x-controller: taskLists
      # x-operation: createTaskList
      tags:
        - Task Lists
      security:
        - cookieAuth: []
      summary: Add a task list.
      requestBody:
        $ref: '#/components/requestBodies/SetTaskList'
      responses:
        201:
          description: Task list created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskLists'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
  /taskLists/{taskListId}:
    parameters:
      - $ref: '#/components/parameters/PathTaskListId'
    put:
      # x-controller: taskLists
      # x-operation: updateTaskList
      tags:
        - Task Lists
      security:
        - cookieAuth: []
      summary: Update a task list.
      requestBody:
        $ref: '#/components/requestBodies/SetTaskList'
      responses:
        200:
          description: Task list updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskList'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
        404:
          description: Not found.
    delete: 
      # x-controller: taskLists
      # x-operation: deleteTaskList
      tags:
        - Task Lists
      security:
        - cookieAuth: []
      summary: Delete a Task List.
      responses:
        204:
          description: Task list deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /tasks:
    get:
      # x-controller: tasks
      # x-operation: getTasks
      tags:
        - Tasks
      security:
        - cookieAuth: []
      summary: Get tasks.
      parameters:
        - name: completed
          in: query
          schema:
            type: boolean
        - name: duration
          in: query
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasks'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    post:
      # x-controller: tasks
      # x-operation: createTask
      tags:
        - Tasks
      security:
        - cookieAuth: []
      summary: Add a task.
      requestBody:
        $ref: '#/components/requestBodies/SetTask'
      responses:
        201:
          description: Task created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
  /tasks/{taskId}:
    parameters:
      - $ref: '#/components/parameters/PathTaskId'
    put:
      # x-controller: tasks
      # x-operation: updateTask
      tags:
        - Tasks
      security:
        - cookieAuth: []
      summary: Update a task.
      requestBody:
        $ref: '#/components/requestBodies/SetTask'
      responses:
        200:
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
        404:
          description: Not found.
    delete: 
      # x-controller: tasks
      # x-operation: deleteTask
      tags:
        - Tasks
      security:
        - cookieAuth: []
      summary: Delete a task.
      responses:
        204:
          description: Task deleted
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /events:
    get:
      # x-controller: events
      # x-operation: getEvents
      tags:
        - Events
      security:
        - cookieAuth: []
      summary: Get events.
      parameters:
        - name: occurred
          in: query
          schema:
            type: string
            format: date-time
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
    post:
      # x-controller: events
      # x-operation: createEvent
      tags:
        - Events
      security:
        - cookieAuth: []
      summary: Add an event.
      requestBody:
        $ref: '#/components/requestBodies/SetEvent'
      responses:
        201:
          description: Event created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
  /events/{eventId}:
    parameters:
      - $ref: '#/components/parameters/PathEventId'
    put:
      # x-controller: events
      # x-operation: updateEvent
      tags:
        - Events
      security:
        - cookieAuth: []
      summary: Update an event.
      requestBody:
        $ref: '#/components/requestBodies/SetEvent'
      responses:
        200:
          description: Event updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
        404:
          description: Not found.
    delete:
      # x-controller: events
      # x-operation: deleteEvent
      tags:
        - Events
      security:
        - cookieAuth: []
      summary: Delete an event.
      responses:
        204:
          description: Event deleted.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
  /notes:
    put:
      # x-controller: notes
      # x-operation: updateNote
      tags:
        - Notes
      security:
        - cookieAuth: []
      summary: Update notes.
      requestBody:
        $ref: '#/components/requestBodies/SetNote'
      responses:
        200:
          description: Note updated.
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Invalid request.
        401:
          description: Not authenticated.
        403:
          description: Access denied.
        404:
          description: Not found.
components:
  parameters:
    PathAccountId:
      name: accountId
      in: path
      required: true
      schema: 
        type: string
    PathUsername:
      name: username
      in: path
      required: true
      schema:
        type: string
    PathTaskListId:
      name: taskListId
      in: path
      required: true
      schema: 
        type: string
    PathTaskId:
      name: taskId
      in: path
      required: true
      schema: 
        type: string
    PathEventId:
      name: eventId
      in: path
      required: true
      schema: 
        type: string
  requestBodies:
    SetTaskList:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskList'
    SetTask:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Task'
    SetEvent:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Event'
    SetNote:
      required: true
      content:
        text/plain:
          schema:
            type: string
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: simplePlanSessionId
  schemas:
    User:
      required:
        - user
      properties:
        user:
          type: object
          properties:
            username:
              type: string
              readOnly: true
            email:
              type: string
              readOnly: true
            name:
              type: string
              readOnly: true
    TaskList:
      type: object
      required:
        - title
      properties:
        listId:
          type: string
          readOnly: true
        title:
          type: string
        tasks:
          type: array
          items:
            type: string
        completed:
          type: string
          format: date-time
          nullable: true
    TaskLists:
      type: array
      items:
        $ref: '#/components/schemas/TaskList'
    Task:
      type: object
      required:
        - title
        - duration
      properties:
        taskId:
          type: string
          readOnly: true
        title:
          type: string
        description:
          type: string
        duration:
          type: integer
        complete:
          type: string
          format: date-time
          nullable: true
    Tasks:
      type: array
      items:
        $ref: '#/components/schemas/Task'
    Event: 
      type: object
      required:
        - title
        - start
        - end
      properties:
        EventId:
          type: string
          readOnly: true
        title:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
    Events:
      type: array
      items:
        $ref: '#/components/schemas/Event'